version: '3.9'

services:
  back-encuestacc:
    build: .
    container_name: back-encuestacc
    command: sh -c "uvicorn app:app --reload --port=8085 --host=0.0.0.0"
    ports:
      - 8085:8085
    volumes:
      - .:/app